services:
  web:
    build: .
    image: wol-manager:latest
    container_name: wol-manager
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    network_mode: "host"  # 使用主机网络模式，这对于Wake-on-LAN功能是必需的
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/data/devices.db
      - PORT=8088  # 添加端口环境变量
